# frozen_string_literal: true

# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

raise 'DO NOT USE SEED!'

# Todo.create(
#   [
#     { content: '柳田 政年', complete: 0 },
#     { content: '佐野 護', complete: 0 },
#     { content: '小松 純典', complete: 0 },
#     { content: '堀川 陽子', complete: 0 },
#     { content: '堀川 武士', complete: 0 },
#     { content: '松原 竹義', complete: 0 },
#     { content: '山崎 詔勝', complete: 0 },
#     { content: '大内 武俊', complete: 0 },
#     { content: '藤村 広重', complete: 0 },
#     { content: '白川 芳尚', complete: 0 },
#     { content: '大塚 美砂', complete: 0 },
#     { content: '茂木 幸郎', complete: 0 },
#     { content: '辻 和広', complete: 0 },
#     { content: '東 茂俊', complete: 0 },
#     { content: '豊田 世弥', complete: 0 },
#     { content: '笠原 永寿', complete: 0 },
#     { content: '浅井 陽一郎', complete: 0 },
#     { content: '吉沢 祐子', complete: 0 },
#     { content: '中野 貢太郎', complete: 0 },
#     { content: '奥野 貢太郎', complete: 0 },
#     { content: '竹内 芳伸', complete: 0 },
#     { content: '花田 十四夫', complete: 0 },
#     { content: '西川 重文', complete: 0 },
#     { content: '後藤 一樹', complete: 0 },
#     { content: '古田 早葉子', complete: 0 },
#     { content: '坂井 裕仁', complete: 0 },
#     { content: '中野 昌光', complete: 0 },
#     { content: '堀江 茂也', complete: 0 },
#     { content: '小野 理江', complete: 0 },
#     { content: '徳田 真里', complete: 0 },
#     { content: '古谷 督彦', complete: 0 },
#     { content: '田代 健生', complete: 0 },
#     { content: '古谷 常一', complete: 0 },
#     { content: '藤村 克三', complete: 0 },
#     { content: '横山 琢司', complete: 0 },
#     { content: '浅野 元信', complete: 0 },
#     { content: '古谷 政年', complete: 0 },
#     { content: '小田 三佐男', complete: 0 },
#     { content: '村瀬 尭道', complete: 0 },
#     { content: '武井 恵治', complete: 0 },
#     { content: '土屋 孝次', complete: 0 },
#     { content: '大場 令', complete: 0 },
#     { content: '久保 友良', complete: 0 },
#     { content: '大平 美津枝', complete: 0 },
#     { content: '山岸 時司', complete: 0 },
#     { content: '下田 美里', complete: 0 },
#     { content: '岡 敬志', complete: 0 },
#     { content: '森田 道和', complete: 0 },
#     { content: '白川 恵', complete: 0 },
#     { content: '松本 俊憲', complete: 0 },
#     { content: '秋田 秋代', complete: 0 },
#     { content: '安井 勝英', complete: 0 },
#     { content: '藤川 敬生', complete: 0 },
#     { content: '谷川 元三', complete: 0 },
#     { content: '山本 興亜', complete: 0 },
#     { content: '小松 良司', complete: 0 },
#     { content: '竹下 勤', complete: 0 },
#     { content: '新田 酉蔵', complete: 0 },
#     { content: '竹本 幸四郎', complete: 0 },
#     { content: '野崎 慶太郎', complete: 0 },
#     { content: '古谷 朋子', complete: 0 },
#     { content: '大森 裕子', complete: 0 },
#     { content: '荻野 生三', complete: 0 },
#     { content: '丹羽 重三郎', complete: 0 },
#     { content: '坂田 安民', complete: 0 },
#     { content: '堀 十四夫', complete: 0 },
#     { content: '奥山 義将', complete: 0 },
#     { content: '小出 成男', complete: 0 },
#     { content: '馬場 育雄', complete: 0 },
#     { content: '高瀬 夕子', complete: 0 },
#     { content: '福原 和久', complete: 0 },
#     { content: '大沢 允彦', complete: 0 },
#     { content: '本間 多栄子', complete: 0 },
#     { content: '細川 敬', complete: 0 },
#     { content: '植田 麻紀', complete: 0 },
#     { content: '千田 三重子', complete: 0 },
#     { content: '緒方 裕恵', complete: 0 },
#     { content: '福岡 美緒', complete: 0 },
#     { content: '野田 常次', complete: 0 },
#     { content: '藤川 真樹', complete: 0 },
#     { content: '横井 紀子', complete: 0 },
#     { content: '堀内 美里', complete: 0 },
#     { content: '本間 十四夫', complete: 0 },
#     { content: '松山 勝行', complete: 0 },
#     { content: '福永 優紀', complete: 0 },
#     { content: '関根 洋昌', complete: 0 },
#     { content: '富田 忠之', complete: 0 },
#     { content: '平山 勝司', complete: 0 },
#     { content: '田上 恵治', complete: 0 },
#     { content: '増田 雅則', complete: 0 },
#     { content: '古谷 俊郎', complete: 0 },
#     { content: '安部 善二', complete: 0 },
#     { content: '土田 十四夫', complete: 0 },
#     { content: '池上 玲子', complete: 0 },
#     { content: '福井 純隆', complete: 0 },
#     { content: '大石 梨華', complete: 0 },
#     { content: '尾崎 聡', complete: 0 },
#     { content: '島田 利克', complete: 0 },
#     { content: '堀内 唯', complete: 0 },
#     { content: '福本 美津枝', complete: 0 }
#   ]
# )
